swagger: '2.0'
info:
  version: "0.0.1"
  title: Example Title
  description: <video><source onerror=alert(1)></video>
paths:
  /:
    get:
      responses:
        200:
          description: Successful response
