swagger: '2.0'
info:
  title: Example yaml.spec
  description: |
    a<style><!--</style><a id="--!><img src=x onerror=alert()>">
paths:
  /accounts:
    get:
      responses:
        '200':
          description: No response was specified
      tags:
        - accounts
      operationId: findAccounts
      summary: Finds all accounts
