swagger: '2.0'
info:
  version: "0.0.1"
  title: Example Title
  description: <iframe src="javascript:alert(1)"></iframe>
paths:
  /:
    get:
      responses:
        200:
          description: Successful response
