swagger: '2.0'
info:
  title: Example yaml.spec
  description: |
    <div*506> <table> <caption> <svg> <title> <table><caption></caption></table> </title> <style><a id="</style><img src=x onerror=alert()>"></a></style> </svg> </caption> </table>
paths:
  /accounts:
    get:
      responses:
        '200':
          description: No response was specified
      tags:
        - accounts
      operationId: findAccounts
      summary: Finds all accounts
