swagger: '2.0'
info:
  version: "0.0.1"
  title: Example Title
  description: <svg on onload=(alert)(document.domain)>
paths:
  /:
    get:
      responses:
        200:
          description: Successful response
