swagger: '2.0'
info:
  title: Example yaml.spec
  description: |
    <style> <a id="</style><img src=x onerror=alert(1)>"></a> </style>
paths:
  /accounts:
    get:
      responses:
        '200':
          description: No response was specified
      tags:
        - accounts
      operationId: findAccounts
      summary: Finds all accounts
