swagger: '2.0'
info:
  version: "0.0.1"
  title: Example Title
  description: <math><mtext><script>alert(1)</script></mtext></math>
paths:
  /:
    get:
      responses:
        200:
          description: Successful response
