swagger: '2.0'
info:
  title: Example yaml.spec
  description: |
    <svg></p><style><a id="</style><img src=1 onerror=alert(1)>">
paths:
  /accounts:
    get:
      responses:
        '200':
          description: No response was specified
      tags:
        - accounts
      operationId: findAccounts
      summary: Finds all accounts
