swagger: '2.0'
info:
  version: "0.0.1"
  title: Example Title
  description: <img onerror=alert('textarea') src=1>
paths:
  /:
    get:
      responses:
        200:
          description: Successful response
